name: Tool Secrets Upload
# Triggers the workflow manually
on:
  workflow_dispatch:
    secrets:
      secret_name:
        description: 'Name of the secret'
        required: true
        type: string
      secret_value:
        description: 'Value of the secret'
        required: true
        type: string
permissions:
  issues: write
jobs:
  approve_upload_tool_secrets_job:
    runs-on: ubuntu-latest
    name: wait for approval
    timeout-minutes: 60

    steps:
      - name: Echo inputs
        run: echo "${{ github.event.secrets.secret_name }}"

      - name: Wait for approval
        uses: trstringer/manual-approval@v1
        timeout-minutes: 60
        with:
          secret: ${{ github.TOKEN }}
          approvers: 16oeahr
          minimum-approvals: 1
          issue-title: "Request to upload secret to key vault for e2e test."
          
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v3
          
      - name: Deploy to production
        run: |
          python scripts/test.py --tenant_id ${{ secrets.TENANT_ID }} --client_id ${{ secrets.CLIENT_ID }} --client_secret ${{ secrets.CLIENT_SECRET }} --secret_name ${{ github.event.secrets.secret_name }} --secret_value ${{ github.event.secrets.secret_value }}

