name: Tool Secrets Upload
# Triggers the workflow manually
on:
  workflow_dispatch:
    inputs:
      secret_name:
        description: 'Name of the secret'
        required: true
        type: string
      secret_value:
        description: 'Value of the secret'
        required: true
        type: string
permissions:
  issues: write
jobs:
  approve_upload_tool_secrets_job:
    runs-on: ubuntu-latest
    name: wait for approval
    timeout-minutes: 60

    steps:
      - name: Echo inputs
        run: echo "${{ github.event.inputs.secret_name }}"

      - name: Wait for approval
        uses: trstringer/manual-approval@v1
        timeout-minutes: 60
        with:
          secret: ${{ github.TOKEN }}
          approvers: 16oeahr
          minimum-approvals: 1
          issue-title: "Request to upload secret to key vault for e2e test."
          
      - name: Deploy to production
        run: echo deploying

